### ISSUE TITLE
bot.connected? returns true when it is not connected

### ISSUE THREAD

**Issue by davidkirwan** [discordrb/discordrb#688]
# Summary

I'm using the Discordrb::Bot.connected? (https://github.com/discordrb/discordrb/blob/88207c209b001b0fcb93089805382b89806563dd/lib/discordrb/bot.rb#L266-L268) function to determine if the bot is still connected, however this seems to always return true even when it is has timed out.

It does occasionally reconnect after a disconnect but eventually fails permanently.

---

## Environment

container: https://github.com/davidkirwan/MakerCulture/blob/master/Dockerfile
kubernetes deployment: https://github.com/davidkirwan/MakerCulture/blob/master/kubernetes/deployment.yaml
cluster: Kubernetes v1.9.1+a0ce1bc657 

**Ruby version:**

```
ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

**Discordrb version:**

```
gem list discordrb

*** LOCAL GEMS ***

discordrb (3.3.0)
discordrb-webhooks (3.3.0)
```

![Screenshot from 2019-12-11 15-42-57](https://user-images.githubusercontent.com/1700165/70636124-eb4c3400-1c2c-11ea-9239-2cd833b0219e.png)
![Screenshot from 2019-12-11 15-47-01](https://user-images.githubusercontent.com/1700165/70636520-90ffa300-1c2d-11ea-8269-5b2df475eba5.png)

**Comment by z64** [comment]
`connected` just checks if 
- An underlying TCP socket connection is open
- The WebSocket protocol handshake has been completed

`connected` does not, for example, inform if there is an active session with Discord

If we lose connection, the socket-level reconnection will happen *very* quickly (milliseconds), so I doubt you would by chance ever observe this to be `false` unless you have explicitly disconnected your bot (`bot.stop`), or have yet to connect it (`bot.run`). Likewise, if we are in an "intermediate" state - such as your network connection to discord is "in the process" of timing out - it will of course still return `true` as well.

The semantics of `connected` seem fine to me. While I'm not sure why this method exists, it appears you are trying to use it to detect network level issues, which it will not (cannot) do; otherwise the library would be handling it, if it could.

**Comment by davidkirwan** [comment]
Cheers @z64 looks like I don't really have a way to check if the bot is connected to discord in that case? maybe I'll create a feature request and try implement some workaround on my end.

**Comment by swarley** [comment]
You can manage state between `ready` and `disconnect` if you feel the need to do so.

**Comment by z64** [comment]
Well, users should not have to handle any connection details at all. That's just a goal of the library.
If you're just going to do something like "if bot is not connected, reconnect", there is no reason the library cannot do this itself, and we do so in every case we can.

You're welcome to take a look if that's the case, but the changes involved need to be in the vein of increasing the library's awareness of a potentially bad state, and handling it accordingly.

As @swarley mentioned, it wouldn't be a bad idea to do something like set up a Docker healthcheck system via `bot.ready`, etc. as a "brute force catch-all" of sorts.

**Comment by z64** [comment]
I took a quick look at https://github.com/davidkirwan/MakerCulture/blob/master/makerculture.rb#L258-L262

And yeah; you can try the following as a mitigation, or something similar:
```rb
# This is called whenever the bot successfully connects (or reconnects) and starts a 
# new session with Discord. This won't be called for *every* reconnection - sometimes 
# we can reconnect and re-use the previous session.
bot.ready { system("touch /tmp/healthy") }

# Part of Discord's gateway protocol.
# This is called whenever we send off our "ping" to keep the connection alive.
# The protocol dynamically tells us how often this is, but in practice this
# is currently always every 41.25 seconds. See `EventContainer#heartbeat`
# for more notes.
bot.heartbeat { system("touch /tmp/healthy") }
  
# Self explanatory; Note this is broken in 3.3.0 and is never called.
# Fixed in master. https://github.com/discordrb/discordrb/pull/611
bot.disconnected { system("rm /tmp/healthy") }
```
I would just be careful about the last one, since even though the Disconnected event will be raised, the library will already be trying to reconnect and *resume* the last session. Killing the process early might mean wasting a session depending on how far it got - note you can only create 1000 sessions per-day. So you probably don't want to `rm` right away.

**Comment by davidkirwan** [comment]
Cheers I'll give this a go @z64 ! 

I suspect its ultimately an issue with the network on the openshift/kubernetes cluster I'm running the bot on.. I've been examining things like ROUTER_DEFAULT_TUNNEL_TIMEOUT in https://docs.openshift.com/container-platform/3.4/architecture/core_concepts/routes.html

But in the meantime a workaround like your suggestion is probably good enough just to get the bot running somewhat regularly again.

**Comment by z64** [comment]
Alrighty, cool. I think we've mostly explored this topic so I'll close this for now.
Feel free to reopen with more details, or open a more specific issue if you find something you think is actionable in the library. There's also our [Discord channel](https://discord.gg/cyK3Hjm) where you can poke others for suggestions, etc.

Thanks for your interest in helping out.
