### ISSUE TITLE
Make `advanced_functionality`/Command Chain Syntax more configurable

### ISSUE THREAD

**Issue by gsbhasin123** [discordrb/discordrb#694]
Currently, advanced_functionality is a great feature (see https://github.com/discordrb/discordrb/wiki/Commands#command-chain-syntax). However, sometimes a user may only want to use one feature, or a feature specific to a command only. This is what I am requesting here.
## Only enable certain features globally
After `advanced_functionality: true` in the bot definition, you should be able to add:
```ruby
advanced_functionality_features: []
```
Where [] is an array of features that can be enabled.

## Only enable per command
To do this, the syntax in `Discordrb::Commands::CommandBot.command()` could be extended to look like:
```ruby
bot.command(:command_name, advanced_functionality: true)
```
This would be an optional arg auto set to false that would enable all advanced functionality for the specific command.

## Only enable certain features *per-command*
This is supposed to be the above, except also except a features array similar to the first example. This imo is *the* most important!

**Comment by z64** [comment]
As discussed in the channel, it is currently not practical for us to further tweak the `CommandBot` API without making the code harder to understand, or the API more complicated to support random use cases. Since it cannot be easily extended by users, or well maintained by developers, it will eventually have a proper review and reimplementation that will hopefully result in something sufficiently powerful.

Such a solution will crop up sometime during the v4 cycle, hopefully landing on something decisive in v5 that will be better all around.

**Comment by gsbhasin123** [comment]
> As discussed in the channel, it is currently not practical for us to further tweak the CommandBot API without making the code harder to understand, or the API more complicated to support random use cases. Since it cannot be easily extended by users, or well maintained by developers, it will eventually have a proper review and reimplementation that will hopefully result in something sufficiently powerful.

I see. Will a feature similar to `advanced_functionality` be available when the new version pops up though?

**Comment by z64** [comment]
It will probably look nothing like the current command bot, so that concept will likely not exist.

The goals of providing a "command bot" primarily revolve around the parser, to which the library will deliver to the (single) most common use case, and as mentioned, have some surface so it can be extended by users.

**Comment by FluorescentGreen5** [comment]
> As discussed in the channel, it is currently not practical for us to further tweak the CommandBot API without making the code harder to understand, or the API more complicated to support random use cases.

True, a use case like this seems oddly specific and doesn't look like it belongs in something that's meant for common use cases:
`!user > bold The user name is:`

`**The user name is:** meew0`

**Comment by gsbhasin123** [comment]
Indeed that isn't. However the quotes feature is, @FluorescentGreen5

**Comment by FluorescentGreen5** [comment]
Hmm, maybe shell splitting shouldn't be considered advanced functionality in the CommandBot revamp. Although, shell splitting can be easily done manually for now.

```
irb(main):001:0> require 'shellwords'
=> true
irb(main):002:0> '.command "something and" "something else"'.shellsplit
=> [".command", "something and", "something else"]```

**Comment by gsbhasin123** [comment]
I know :+1: 
Should be inbuilt though
